In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Neil\Documents\Projects\Electoral-PH\Electoral-PH\image_creator\static\data\2004_Presidential.csv', index_col=0)

In [3]:
df.head()

,province_id,Gloria_Arroyo,Fernando_Poe_Jr,Panfilo_Lacson,Raul_Roco,Eddie_Villanueva
0,1,32644,50866,11256,2251,3741
1,2,138402,66125,12585,7152,18680
2,3,100998,61949,10905,4643,15649
3,4,87197,84080,11247,8830,10158
4,5,172777,74711,23079,197345,11802

In [4]:
df.columns[1:]

Index(['Gloria_Arroyo', 'Fernando_Poe_Jr', 'Panfilo_Lacson', 'Raul_Roco',
       'Eddie_Villanueva'],
      dtype='object')

In [5]:
master_df = df.melt(id_vars=['province_id'], value_vars=['Gloria_Arroyo', 'Fernando_Poe_Jr', 'Panfilo_Lacson', 'Raul_Roco', 'Eddie_Villanueva'])

In [6]:
master_df['year'] = '2004'
master_df['position'] = 'President'

In [7]:
master_df = master_df[['year', 'position', 'province_id', 'variable','value']]

In [8]:
master_df = master_df.rename(columns={'variable': 'candidate', 'value':'votes'})

### frfr

In [9]:
import os

import pandas as pd

In [10]:
DIR = r'C:\Users\Neil\Documents\Projects\Electoral-PH\Electoral-PH\image_creator\static\data'

In [11]:
files = os.listdir(DIR)[:-5]
election_data = []
for file in files:
    print(file[:4])
    if 'Reps' not in file:
        print(election_data)
        election_data.append(file)

2004
[]
2004
2010
['2004_Presidential.csv']
2010
2010
['2004_Presidential.csv', '2010_Presidential.csv']
2016
['2004_Presidential.csv', '2010_Presidential.csv', '2010_VicePresidential.csv']
2016
2016
['2004_Presidential.csv', '2010_Presidential.csv', '2010_VicePresidential.csv', '2016_Presidential.csv']
2022
['2004_Presidential.csv', '2010_Presidential.csv', '2010_VicePresidential.csv', '2016_Presidential.csv', '2016_VicePresidential.csv']
2022
2022
['2004_Presidential.csv', '2010_Presidential.csv', '2010_VicePresidential.csv', '2016_Presidential.csv', '2016_VicePresidential.csv', '2022_Presidential.csv']

In [12]:
print(files)

['2004_Presidential.csv', '2004_Reps.csv', '2010_Presidential.csv', '2010_Reps.csv', '2010_VicePresidential.csv', '2016_Presidential.csv', '2016_Reps.csv', '2016_VicePresidential.csv', '2022_Presidential.csv', '2022_Reps.csv', '2022_VicePresidential.csv']

In [28]:
dfs = []
for file in election_data:
    df = pd.read_csv(DIR+'/'+file, index_col=0)
    cols = list(df.columns[1:])
    print(cols)
    if 'Province' in cols:
        cols.remove("Province")
    print(file)
    #df.melt(id_vars=['province_id'], value_vars=['Gloria_Arroyo', 'Fernando_Poe_Jr', 'Panfilo_Lacson', 'Raul_Roco', 'Eddie_Villanueva'])
    df = df.melt(id_vars=['province_id'], value_vars=cols)

    df['year'] = file[:4]
    df['position'] = "Vice_President" if 'Vice' in file else "President"
    df.rename(columns={'variable': 'candidate', 'value':'votes'}, inplace=True)
    
    dfs.append(df)

['Gloria_Arroyo', 'Fernando_Poe_Jr', 'Panfilo_Lacson', 'Raul_Roco', 'Eddie_Villanueva']
2004_Presidential.csv
['Benigno_Aquino', 'Joseph_Estrada', 'Manny_Villar', 'Gilbert_Teodoro', 'Eddie_Villanueva', 'Dick_Gordon', 'Nicanor_Perlas', 'Jamby_Madrigal', 'John_delosReyes']
2010_Presidential.csv
['Jejomar_Binay', 'Mar_Roxas', 'Loren_Legarda', 'Bayani_Fernando', 'Edu_Manzano', 'Perfecto_Yasay', 'Jay_Sonza', 'Dominador_Chipeco']
2010_VicePresidential.csv
['Province', 'Rodrigo_Duterte', 'Mar_Roxas', 'Grace_Poe', 'Jejomar_Binay', 'Miriam_Santiago']
2016_Presidential.csv
['Province', 'Leni_Robredo', 'Bongbong_Marcos', 'Alan_Cayetano', 'Chiz_Escudero', 'Sonny_Trillanes', 'Gringo_Honasan']
2016_VicePresidential.csv
['Province', 'Bongbong_Marcos', 'Leni_Robredo', 'Manny_Pacquiao', 'Isko_Moreno', 'Panfilo_Lacson', 'Faisal_Mangondato', 'Ernesto_Abella', 'Leody_deGuzman', 'Norberto_Gonzales', 'Jose_Montemayor']
2022_Presidential.csv
['Province', 'Sara_Duterte', 'Kiko_Pangilinan', 'Tito_Sotto', 'Willie_Ong', 'Lito_Atienza', 'Manny_Lopez', 'Walden_Bello', 'Carlos_Serapio', 'Rizalito_David']
2022_VicePresidential.csv

In [29]:
master_df = pd.concat(dfs)

In [30]:
master_df = master_df[['year', 'position', 'province_id', 'candidate','votes']]

In [31]:
master_df

     year        position  province_id       candidate   votes
0    2004       President            1   Gloria_Arroyo   32644
1    2004       President            2   Gloria_Arroyo  138402
2    2004       President            3   Gloria_Arroyo  100998
3    2004       President            4   Gloria_Arroyo   87197
4    2004       President            5   Gloria_Arroyo  172777
..    ...             ...          ...             ...     ...
967  2022  Vice_President          111  Rizalito_David     392
968  2022  Vice_President          112  Rizalito_David    1281
969  2022  Vice_President          113  Rizalito_David     863
970  2022  Vice_President          114  Rizalito_David     563
971  2022  Vice_President           65  Rizalito_David     191

[5508 rows x 5 columns]

In [32]:
colors_df = pd.read_csv(r'C:\Users\Neil\Documents\Projects\Electoral-PH\Electoral-PH\image_creator\static\data\colors.csv')
colors_df = colors_df.astype({"year":str})
colors_df.head()

   year         candidate    color
0  2004     Gloria_Arroyo  #B0E0E6
1  2004   Fernando_Poe_Jr  #0038A8
2  2004    Panfilo_Lacson  #C4C4FF
3  2004         Raul_Roco  #9683EC
4  2004  Eddie_Villanueva  #3F9727

In [33]:
colors_df.dtypes

year         object
candidate    object
color        object
dtype: object

In [34]:
master_df.head(10)

   year   position  province_id      candidate   votes
0  2004  President            1  Gloria_Arroyo   32644
1  2004  President            2  Gloria_Arroyo  138402
2  2004  President            3  Gloria_Arroyo  100998
3  2004  President            4  Gloria_Arroyo   87197
4  2004  President            5  Gloria_Arroyo  172777
5  2004  President            6  Gloria_Arroyo   92992
6  2004  President            7  Gloria_Arroyo   15018
7  2004  President            8  Gloria_Arroyo   16755
8  2004  President           11  Gloria_Arroyo   79702
9  2004  President           12  Gloria_Arroyo   65955

In [35]:
master_df = pd.merge(master_df, colors_df[['year', 'candidate', 'color']], on=['year', 'candidate'], how='left')

In [36]:
province_df = pd.read_csv(r'C:\Users\Neil\Documents\Projects\Electoral-PH\Electoral-PH\image_creator\static\data\Provinces.csv',index_col=0)
province_df.head()

   province_id          Province
0            1              Abra
1            2  Agusan del Norte
2            3    Agusan del Sur
3            4             Aklan
4            5             Albay

In [37]:
master_df = pd.merge(master_df, province_df[['province_id', 'Province']], on=['province_id'], how='left')

In [38]:
master_df = master_df[['year', 'position', 'Province', 'color','candidate','votes']]

In [39]:
master_df = master_df.rename(columns={'Province':'province'})

In [40]:
master_df.to_csv(r'C:\Users\Neil\Documents\Projects\Electoral-PH\Electoral-PH\image_creator\static\data\master_data.csv')