In [1]:
import pandas as pd

In [5]:
df = pd.read_csv(r'C:\Users\Neil\Documents\Projects\Electoral-PH\Electoral-PH\image_creator\static\data\2004_Presidential.csv', index_col=0)

In [6]:
df.head()

,province_id,Gloria_Arroyo,Fernando_Poe_Jr,Panfilo_Lacson,Raul_Roco,Eddie_Villanueva
0,1,32644,50866,11256,2251,3741
1,2,138402,66125,12585,7152,18680
2,3,100998,61949,10905,4643,15649
3,4,87197,84080,11247,8830,10158
4,5,172777,74711,23079,197345,11802

In [28]:
df.columns[1:]

Index(['Gloria_Arroyo', 'Fernando_Poe_Jr', 'Panfilo_Lacson', 'Raul_Roco',
       'Eddie_Villanueva'],
      dtype='object')

In [10]:
master_df = df.melt(id_vars=['province_id'], value_vars=['Gloria_Arroyo', 'Fernando_Poe_Jr', 'Panfilo_Lacson', 'Raul_Roco', 'Eddie_Villanueva'])

In [11]:
master_df['year'] = '2004'
master_df['position'] = 'President'

In [13]:
master_df = master_df[['year', 'position', 'province_id', 'variable','value']]

In [15]:
master_df = master_df.rename(columns={'variable': 'candidate', 'value':'votes'})

### frfr

In [17]:
import os

import pandas as pd

In [23]:
DIR = r'C:\Users\Neil\Documents\Projects\Electoral-PH\Electoral-PH\image_creator\static\data'

In [30]:
files = os.listdir(DIR)[:-4]
election_data = []
for file in files:
    print(file[:4])
    if 'Reps' not in file:
        election_data.append(file)
        if 'Vice' in file:
            print(f'VICE PRES: {file}')
        else:
            print(f'PRES: {file}')

2004
PRES: 2004_Presidential.csv
2004
2010
PRES: 2010_Presidential.csv
2010
2010
VICE PRES: 2010_VicePresidential.csv
2016
PRES: 2016_Presidential.csv
2016
2016
VICE PRES: 2016_VicePresidential.csv
2022
PRES: 2022_Presidential.csv
2022
2022
VICE PRES: 2022_VicePresidential.csv

In [46]:
dfs = []
for file in election_data:
    df = pd.read_csv(DIR+'/'+file, index_col=0)
    cols = df.columns[1:]
    #df.melt(id_vars=['province_id'], value_vars=['Gloria_Arroyo', 'Fernando_Poe_Jr', 'Panfilo_Lacson', 'Raul_Roco', 'Eddie_Villanueva'])
    df = df.melt(id_vars=['province_id'], value_vars=cols)

    df['year'] = file[:4]
    df['position'] = "Vice_President" if 'Vice' in file else "President"
    df.rename(columns={'variable': 'candidate', 'value':'votes'}, inplace=True)
    
    dfs.append(df)

In [47]:
master_df = pd.concat(dfs)

In [48]:
master_df = master_df[['year', 'position', 'province_id', 'candidate','votes']]

In [49]:
master_df

      year        position  province_id       candidate   votes
0     2004       President            1   Gloria_Arroyo   32644
1     2004       President            2   Gloria_Arroyo  138402
2     2004       President            3   Gloria_Arroyo  100998
3     2004       President            4   Gloria_Arroyo   87197
4     2004       President            5   Gloria_Arroyo  172777
...    ...             ...          ...             ...     ...
1075  2022  Vice_President          111  Rizalito_David     392
1076  2022  Vice_President          112  Rizalito_David    1281
1077  2022  Vice_President          113  Rizalito_David     863
1078  2022  Vice_President          114  Rizalito_David     563
1079  2022  Vice_President           65  Rizalito_David     191

[5936 rows x 5 columns]

In [59]:
colors_df = pd.read_csv(r'C:\Users\Neil\Documents\Projects\Electoral-PH\Electoral-PH\image_creator\static\data\colors.csv')
colors_df = colors_df.astype({"year":str})
colors_df.head()

   year         candidate    color
0  2004     Gloria_Arroyo  #B0E0E6
1  2004      Fernando_Poe  #0038A8
2  2004    Panfilo_Lacson  #C4C4FF
3  2004         Raul_Roco  #9683EC
4  2004  Eddie_Villanueva  #3F9727

In [62]:
colors_df.dtypes

year         object
candidate    object
color        object
dtype: object

In [53]:
master_df.head(10)

   year   position  province_id      candidate   votes
0  2004  President            1  Gloria_Arroyo   32644
1  2004  President            2  Gloria_Arroyo  138402
2  2004  President            3  Gloria_Arroyo  100998
3  2004  President            4  Gloria_Arroyo   87197
4  2004  President            5  Gloria_Arroyo  172777
5  2004  President            6  Gloria_Arroyo   92992
6  2004  President            7  Gloria_Arroyo   15018
7  2004  President            8  Gloria_Arroyo   16755
8  2004  President           11  Gloria_Arroyo   79702
9  2004  President           12  Gloria_Arroyo   65955

In [66]:
master_df = pd.merge(master_df, colors_df[['year', 'candidate', 'color']], on=['year', 'candidate'], how='left')

In [74]:
province_df = pd.read_csv(r'C:\Users\Neil\Documents\Projects\Electoral-PH\Electoral-PH\image_creator\static\data\Provinces.csv',index_col=0)
province_df.head()

   province_id          Province
0            1              Abra
1            2  Agusan del Norte
2            3    Agusan del Sur
3            4             Aklan
4            5             Albay

In [76]:
master_df = pd.merge(master_df, province_df[['province_id', 'Province']], on=['province_id'], how='left')

In [77]:
master_df = master_df[['year', 'position', 'Province', 'color','candidate','votes']]

In [79]:
master_df = master_df.rename(columns={'Province':'province'})

In [80]:
master_df.to_csv(r'C:\Users\Neil\Documents\Projects\Electoral-PH\Electoral-PH\image_creator\static\data\master_data.csv')